### PR TITLE
Add snapshot operations for virtual machines

### PR DESCRIPTION
**Pull request by czee**
New operations to list, create, remove and revert snapshots for a virtual machine.

### CODE REVIEW

**Comment by snobear** [comment]
Sweet! I'll test this out when I'm back in next week.

**Comment by snobear** [comment]
@czee Looks good!  Couple of things though:

1) listSnapshots

When there are no snapshots, can you have it say 0 snapshots or similar?  Currently it just shows the output fields, e.g.
```
$ ezmomi listSnapshots --vm web01
VM                   Snapshot             Create Time
```

2) The output looks a little off formatting-wise, at least for my test here
```
ezmomi listSnapshots --vm test44
VM                   Snapshot             Create Time
'vim.VirtualMachine:vm-4890' test44_snapshot      <20
```

On a side note, we've been a little inconsistent with the parameter names in the subcommands.  Clone uses `--hostname` to identify a VM name, the power operations use `--name`, and we're using `--vm` here.  Not sure what I prefer, but eventually we should make it consistent across the board.

**Comment by czee** [comment]
Thanks. I have a couple of amendments:

1) Maybe here there should be a --------- line underneath the header row?

2) Let's put this in a second patch where we format all the print output consistently with row headings?

With the inconsistent parameter names, we should also have a separate commit to switch to using --vm for the VM name. Using --name is just confusing when adding other operations. Again, this is probably left for a separate commit.

**Comment by czee** [comment]
Ok I've changed it to explicitly state there are no snapshots.

**Comment by snobear** [comment]
> Ok I've changed it to explicitly state there are no snapshots.

Cool.  I did a git pull but didn't see any changes, but maybe you didn't push it to GitHub yet.  (I'm testing your master branch from https://github.com/czee/ezmomi.git) 

I could go either way on the ----- line. I vote to leave it out.  The `ezmomi list` command doesn't ave a line so we'll stick with no line.

Yes, we can do a separate pull request for making the print output consistent.  But the output per 2) in my original comment looks funky...The "<20" for Create Time makes me wonder if `snapshot.createTime` is undefined?

I agree - I'll merge this pull request once 1 and 2 per my original list above are fixed up. Yes, let's address the inconsistent param names in another pull request.  Since that would be a breaking change, we can roll this out as ezmomi 1.0.  It would include #43 #44 and the other potential PR's mentioned here.  Looping in @bsherman in case he has any additional input.

**Comment by czee** [comment]
Sorry, I think I pushed the wrong commit earlier. The next pull request will be for the formatting fix.

**Comment by czee** [comment]
The fix for issue (2) is in pull request #45 now

**Comment by czee** [comment]
In addition to the changes for 1.0, I guess that the docs feature request should at least have some basic documentation completed before release.

**Comment by snobear** [comment]
Thanks @czee I'll take a look this week as things free up.

**Comment by snobear** [comment]
@czee Looking great. I'll pull in #45 since it has everything from this PR too.

**Comment by snobear** [comment]
@czee merged.  Could you add another PR with a section in the docs for these operations?

**Comment by czee** [comment]
Did you mean in the README? We should have proper docs set up. Do you have an external contact? Like email / IRC?

**Comment by snobear** [comment]
Yeah I was thinking the readme, but I agree that proper docs are needed.  I just started using slack, username ashby.  My email is jashby2 AT gmail.com

**Comment by czee** [comment]
You can look at the initial docs I have in my repository on the docs branch. I'm not quite sure if this is what you're after though.

**Pull request merged**
