### PR TITLE
Adding flag to disable ssl warning.

### PR DESCRIPTION
**Pull request by murarisumit**
Use: --no_ssl_verify to disable ssl related warnings.

E.g. : ezmomi list --no_ssl_verify --type Network

### CODE REVIEW

**Comment by murarisumit** [comment]
Fixed typo causing pep8 warning.

**Comment by snobear** [comment]
@murarisumit awesome, thanks. One small nitpicky change - can you have the param be all dashes: `--no-ssl-verify` instead of underscores?

**Comment by snobear** [comment]
Looks like there was a `.vscode/settings.json` file added in the last commit. Can you delete that and then we should be all set.

**Comment by murarisumit** [comment]
ah, stupid mistakes !!

**Comment by snobear** [comment]
merged the other PR.

**Pull request closed without merging**
