### PR TITLE
Add the --dhcp option to the clone subcommand

### PR DESCRIPTION
**Pull request by jctanner**
Addresses #3
This is my first foray into the vsphere api objects, so I did a bit of shooting in the dark on how to accomplish DHCP. Please let me know what you would like revised in this patch and I would be happy to do so.

1) Should passing IPs in the arguments override the --dhcp option or vice versa?
2) Should multiple nics with both static and DHCP be allowed?

### CODE REVIEW

**Comment by snobear** [comment]
@jctanner Are you still interested in finishing this one out?

**Comment by snobear** [comment]
Haven't heard from @jctanner so closing this. I appreciate the PR and will reference your changes when implementing the dhcp feature.

**Comment by derchrisuk** [comment]
I don't want to create a new issue for this, so I add my comments here.
I'm also looking for a DHCP option.
When I played around with the pyVmomi clone samples, I could get a new cloned VM with DHCP, as my source Template has been configured with DHCP.
Would like to have this option here as well.
At the moment I have to come up with some side part solution for the Fixed IP assignment.
But we have a DHCP pool for our VMs, and would like to use that.
I already modified this one here to get me the IP from a VM once it has been cloned.

**Comment by iahmad-khan** [comment]
hi , any update?  creating vm from template using dhcp

**Comment by derchrisuk** [comment]
If I have some time I can pull out the changes I did on my side.

**Pull request closed without merging**
